title: Vince Pergolizzi
description: > # this means to ignore newlines until "baseurl:"
  Personal blog of Vince Pergolizzi Software Engineer
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://vincepergolizzi.com" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
disqus:
  shortname: https-vincepergolizzi-com
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
