title: Vince Pergolizzi
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Personal blog of Vince Pergolizzi Software Engineer
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://vincepergolizzi.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: vp89
github_username:  vp89

# Build settings
disqus:
  shortname: https-vincepergolizzi-com
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
